local map = vim.keymap.set
local harpoon_mark = require("harpoon.mark")
local harpoon_ui = require("harpoon.ui")

map("n", "ha", function()
    harpoon_mark.add_file()
end)
map("n", "hm", function()
    harpoon_ui.toggle_quick_menu()
end)
map("n", "hn", function()
    harpoon_ui.nav_next()
end)
map("n", "he", function()
    harpoon_ui.nav_prev()
end)
