require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "html",
        "javascript",
        "typescript",
        "lua",
        "css",
        "php",
        "jsdoc",
        "json",
        "tsx",
        "markdown",
        "markdown_inline",
        "vim",
        "bash",
        "prisma",
        "regex",
    },
    auto_install = true,
    highlight = { enable = true },
    rainbow = { enable = true, disable = { "html" } },
    autopairs = { enable = true },
    autotag = { enable = true },
    incremental_selection = { enable = true },
    indent = { enable = true, disable = { "yaml" } },
    markid = { enable = true },
    textobjects = {
        select = {
            enable = true,
            lookahead = true,
            keymaps = {
                ["oa"] = { query = "@assignment.outer", desc = "Select outer part of the assignment" },
                ["ia"] = { query = "@assignment.inner", desc = "Select inner part of the assignment" },
                ["la"] = { query = "@assignment.lhs", desc = "Select left hand side of the assignment" },
                ["ra"] = { query = "@assignment.rhs", desc = "Select right hand side of the assignment" },

                ["af"] = { query = "@function.outer", desc = "Select outer part of the function" },
                ["if"] = { query = "@function.inner", desc = "Select inner part of the function" },
            },
        },
        swap = {
            enable = true,
            swap_next = { ["<leader>sn"] = "@parameter.inner" },
            swap_previous = { ["<leader>sp"] = "@parameter.inner" },
        },
    },
    ignore_install = { "help" },
})
