require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"html",
		"javascript",
		"typescript",
		"lua",
		"css",
		"php",
		"jsdoc",
		"json",
		"tsx",
		"markdown",
		"markdown_inline",
		"vim",
		"bash",
		"prisma",
		"regex",
	},
	auto_install = true,
	highlight = { enable = true },
	rainbow = { enable = true, disable = { "html" } },
	autopairs = { enable = true },
	autotag = { enable = true },
	incremental_selection = { enable = true },
	indent = { enable = true, disable = { "yaml" } },
	markid = { enable = true },
	textobjects = {
		select = {
			enable = true,
			lookahead = true,
			keymaps = {
				["af"] = "@function.outer",
				["if"] = "@function.inner",
				["aC"] = "@class.outer",
				["iC"] = "@class.inner",
				["ac"] = "@conditional.outer",
				["ic"] = "@conditional.inner",
				["ab"] = "@block.outer",
				["ib"] = "@block.inner",
				["al"] = "@loop.outer",
				["il"] = "@loop.inner",
				["is"] = "@statement.inner",
				["as"] = "@statement.outer",
				["ad"] = "@comment.outer",
				["am"] = "@call.outer",
				["im"] = "@call.inner",
			},
		},
		swap = {
			enable = true,
			swap_next = { ["<leader>sn"] = "@parameter.inner" },
			swap_previous = { ["<leader>sp"] = "@parameter.inner" },
		},
	},
	ignore_install = { "help" },
})
