#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d I II III IV V
		let name++
	done
}
# workspace 1 (Terminals)
declare -a terminal=(kitty)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done
    
# workspace 3 (Files)
declare -a filem=(dolphin)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done
    
workspaces
config top_padding 50
config window_gap 10

config single_monocle true
config focused_border_color "#68819A"
config normal_border_color "#282c34"
config border_width 2
config borderless_monocle true
config border_radius 8

config split_ratio 0.52
config gapless_monocle true
rule -a Screenkey manage=off

# autostart
nm-applet &
xsetroot -cursor_name left_ptr &
pkill polybar
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/.config/wallpaper/main.jpg &
picom --experimental-backends &
unclutter -idle 10 &
betterclockscreen -u ~/.config/wallpaper/main.jpg &
