#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d I II III IV V
		let name++
	done
}
# workspace 1 (Terminals)
declare -a terminal=(kitty)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done
    
# workspace 3 (Note)
declare -a filem=(notion-app)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done
    
bspc rule -a 'Org.gnome.Nautilus' focus=on state=floating
    
workspaces
bspc config window_gap 12
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config border_width 1
bspc config split_ratio 0.7
bspc config top_padding 0
bspc config focused_border_color  "#1a1a1a"
bspc config normal_border_color  "#101010"

rule -a Screenkey manage=off

# autostart
nm-applet &
xsetroot -cursor_name left_ptr &
pkill polybar
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/.config/wallpaper/bg.jpg
picom --experimental-backends &
unclutter -idle 10 &
betterlockscreen -u ~/.config/wallpaper/bg.jpg
ibus-daemon 
