#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

workspaces() {
    name=1
    for monitor in $(bspc query -M); do
        bspc monitor "${monitor}" -n "$name"
		if [[ "$name" -eq 1 ]]; then
			bspc monitor "${monitor}"	-d I II III IV V VI
		else
			bspc monitor "${monitor}"	-d VI VII VIII IX
		fi
        name=$((name + 1))
    done
}

# Application rules
bspc rule -a kitty desktop=^1 follow=on
bspc rule -a firefox desktop=^2 follow=on
bspc rule -a "YouTube Music" desktop=^3 follow=on
bspc rule -a "Notion" desktop=^4 follow=on
bspc rule -a "Postman" desktop=^5 follow=on
bspc rule -a steam desktop=^6 follow=on

# apps in float mode
bspc rule -a Nemo state=floating follow=on center=true rectangle=900x625+0+0
bspc rule -a Nitrogen state=floating focus=on center=true
bspc rule -a "Nwg-look" state=floating focus=on center=true

workspaces
bspc config window_gap 12
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config border_width 2
bspc config split_ratio 0.640
bspc config top_padding 42
bspc config normal_border_color "#3f3f3f"
bspc config focused_border_color "#FBF1C7"
bspc rule -a Screenkey manage=off

# autostart
nm-applet &
xsetroot -cursor_name left_ptr &
pkill polybar
~/.config/polybar/launch.sh &
nitrogen --restore &
picom &
unclutter -idle 10 &
udiskie &
ibus-daemon
