[font]
size = 14

builtin_box_drawing = true

normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }

offset = { x = 0, y = 1 }
glyph_offset = { x= 0, y= 1 }
