#!/bin/bash

player_status=$(playerctl status 2> /dev/null)
# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    echo "%{F#A9E5BC} 󱖒 %{F-}"
elif [[ $player_status = "Paused" ]]; then
    echo "%{F#999999} 󱖑 %{F-}"
else
    echo ""
fi
