#!/bin/bash

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
    metadata="$(playerctl metadata title)"
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    echo "%{T5}%{F#FFFFFF} $metadata%{F-}"
elif [[ $player_status = "Paused" ]]; then
    echo "%{T5}%{F#999999} $metadata%{F-}"
else
    echo ""
fi


