#!/bin/bash

title_lenght=8
artist_lenght=3

# Get the title and artist of the currently playing media using Playerctl
title=$(playerctl metadata --format "{{ title }}" 2>/dev/null)
artist=$(playerctl metadata --format "{{ artist }}" 2>/dev/null)
word_count=$(printf "$title" | wc -w)
limit=$((title_lenght*4))

# Check if title is empty (no media player found)
if [ -z "$title" ]; then
    echo "輸 "
else
    # Truncate the title if it exceeds the maximum length
    if [ $word_count -gt $title_lenght ]; then
        title=${title:0:limit}...
    fi
    if [ ${#artist} -gt $artist_lenght ]; then
        artist=$(echo "$artist" | sed -r 's/([a-zA-Z])[a-zA-Z]+/\1/g' | tr -d ' ' | tr '[:lower:]' '[:upper:]')
    fi

	echo "$title"
fi
