#!/bin/bash

title_lenght=40
artist_lenght=12

# Get the title and artist of the currently playing media using Playerctl
title=$(playerctl metadata --format "{{ title }}" 2>/dev/null)
artist=$(playerctl metadata --format "{{ artist }}" 2>/dev/null)

# Check if title is empty (no media player found)
if [ -z "$title" ]; then
    echo " "
else
    # Truncate the title if it exceeds the maximum length
    if [ ${#title} -gt $title_lenght ]; then
        title=${title:0:$title_lenght}...
    fi
    if [ ${#artist} -gt $artist_lenght ]; then
        artist=$(echo "$artist" | sed -r 's/([a-zA-Z])[a-zA-Z]+/\1/g' | tr -d ' ' | tr '[:lower:]' '[:upper:]')
    fi

    # Print the title and artist with a Font Awesome icon
    echo "$title - $artist"
fi
