#!/bin/bash
# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu \
-hide-scrollbar true \
-bw 0 \
-theme-str "*{font: \"Iosevka Nerd Font 14\";}\
window {width: 180; height: 160;}\
mainbox {children: [listview];} element {padding: 0; horizontal-align: 0.2;}" \
-xoffset -12 -yoffset 53 \
-location 3 \
<<< "  Lock|  Reboot|  Shutdown")"
case "$MENU" in
    *Lock) betterlockscreen -l ;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff
esac
